config/routes.rb
Rails.application.routes.draw do
  root 'tops#index'
  get 'create_room', to: 'tops#create_room'
  get 'room/:id', to: 'tops#show', as: 'show_room'

end

app/models/chat_room.rb
class ChatRoom < ActiveRecord::Base
end

app/models/top.rb
class Top < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/chat_controller.rb
# coding: utf-8

class ChatController < WebsocketRails::BaseController
  # initialize_session はwebsocket接続時に実行される処理
  def initialize_session
    logger.debug("==========================================================================================initialize chat controller==========================================================================================")
    @redis = Redis.new(host: 'localhost', port: 6379)
    controller_store[:redis] = @redis
  end

  def connect_user
    logger.debug("========================================================================connected user==========================================================================================")
    logger.debug("************************************************************#{request.fullpath}************************************************************")
    rid = session[:room_id]
    talks = controller_store[:redis].lrange rid, 0,100
    logger.debug("************************************************************#{session.keys}************************************************************")
    talks.each do |message|
      msg = ActiveSupport::HashWithIndifferentAccess.new(eval(message))
      # broadcast_message :new_message, msg
      send_message :new_message, msg
    end
  end

  def new_message
    logger.debug("============================================================================================================Call new_message : #{message}==========================================================================================")
    logger.debug("============================================================================================================Call new_message : #{message[:room_id]}==========================================================================================")
    room_id = message[:room_id]
    message[:time] = Time.now.strftime("%Y/%m/%d %H:%M").to_s
    #controller_store[:redis].del gid   消す時はこれ。（ただのメモ）
    controller_store[:redis].rpush room_id, message
    # broadcast_message :new_message, message
    WebsocketRails["#{room_id}"].trigger(:new_message, message)
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  # before_action :set_top, only: [:show, :edit, :update, :destroy]

  # GET /tops
  # GET /tops.json
  def index
    @chat_rooms = ChatRoom.all.order(id: :desc)
  end

  def create_room
    @chat_room = ChatRoom.create!
  end

  # GET /tops/1
  # GET /tops/1.json
  def show
    @chat_room = ChatRoom.find params[:id]
    session[:room_id] = @chat_room.id
  end

  # GET /tops/new
  def new
    @chat_room = ChatRoom.create

    respond_to do |format|
      if @chat_room
        format.html { redirect_to @top, notice: 'Top was successfully created.' }
        format.json { render json: @chat_room.id, flash: @chat_room }
      else
        format.html { render :new }
        format.json { render json: @top.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /tops/1/edit
  def edit
  end

  # POST /tops
  # POST /tops.json
  def create
    @chat_room = ChatRoom.create

      binding.pry
    respond_to do |format|
      if @chat_room
        format.html { redirect_to @top, notice: 'Top was successfully created.' }
        format.json { render json: @chat_room.id, flash: @chat_room }
      else
        format.html { render :new }
        format.json { render json: @top.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tops/1
  # PATCH/PUT /tops/1.json
  def update
    respond_to do |format|
      if @top.update(top_params)
        format.html { redirect_to @top, notice: 'Top was successfully updated.' }
        format.json { render :show, status: :ok, location: @top }
      else
        format.html { render :edit }
        format.json { render json: @top.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tops/1
  # DELETE /tops/1.json
  def destroy
    @top.destroy
    respond_to do |format|
      format.html { redirect_to tops_url, notice: 'Top was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_top
      @top = ChatRoom.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def top_params
      params[:top]
    end
end

app/controllers/websocket_chat_controller.rb
class WebsocketChatController < WebsocketRails::BaseController
  def message_recieve
    # クライアントからのメッセージを取得
    recieve_message = message()

    # websocket_chatイベントで接続しているクライアントにブロードキャスト
    broadcast_message(:websocket_chat, recieve_message)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Html5ApiSample</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tops/_form.html.erb
<%= form_for(@top) do |f| %>
  <% if @top.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@top.errors.count, "error") %> prohibited this top from being saved:</h2>

      <ul>
      <% @top.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tops/_room.erb
<li <%= 'class=animate' if initialized.present? %>>
  <%= link_to show_room_path(room.id) do %>
    <span class="room_num"><%= room.id %></span>
  <% end %>
</li>

app/views/tops/create_room.js.erb
$('#chat_rooms').prepend($("<%= j render partial: 'room', locals: {room: @chat_room, initialized: true} %>"));

app/views/tops/edit.html.erb
<h1>Editing Top</h1>

<%= render 'form' %>

<%= link_to 'Show', @top %> |
<%= link_to 'Back', tops_path %>

app/views/tops/index.html.erb
<div class="container">
  <div>
    <%= link_to create_room_path, remote: true, class: 'create_room' do %>
      <span class="icon_plus">＋</span>
    <% end %>
  </div>

  <ul id="chat_rooms" class="chat_rooms">
    <% Array(@chat_rooms).each do |room| %>
      <%= render partial: 'room', locals: {room: room, initialized: false} %>
    <% end %>
  </ul>
</div>

<!-- <ul id="chat_area"></ul>

<input type="text" name="" value="" id="comment">
<input type="button" value="送信" id="send">

<script>
  var ws_rails = new WebSocketRails('localhost:3000/websocket');

  // メッセージ受信時の処理
  ws_rails.bind("websocket_chat", function(message){
    var message_li = document.createElement("li");
    message_li.textContent = message;
    document.getElementById("chat_area").appendChild(message_li);
  });

  // メッセージ送信時の処理
  document.getElementById("send").onclick =  function(){
    var comment = document.getElementById("comment").value;
    ws_rails.trigger("websocket_chat", comment);
  };
</script> -->

app/views/tops/new.html.erb
<h1>New Top</h1>

<%= render 'form' %>

<%= link_to 'Back', tops_path %>

app/views/tops/show.html.erb
<div id="room_id" style="display: none;"><%= @chat_room.id %></div>
<div id="timeline">
  <div id="chat" data-uri="<%= request.host %>:3001/websocket">
    <ul id="messages">
    </ul>
  </div>
  </div>
</div>

<form id="chat_form" action="show_submit" method="get" accept-charset="utf-8">
<div class="form-group">
    <input class="form-control" type="text" name="" value="" placeholder="" id="msgbody">
    <input class="form-control btn btn-primary" type="button" name="" value="send" id="send">
  </div>
</form>